-- Auto-generated from storefront catalog. Re-run: node scripts/generate-seed.mjs

insert into public.products (
  id, name, aka, sub, tag, cat, category_label, cas, mw, lot, form, purity,
  storage_lyophilised, storage_reconstituted, reconstitution, composition,
  perks, research_focus, description, story, hue, active, sort_order
) values
(
  'reta',
  'Retatrutide',
  array['Reta', 'LY3437943']::text[],
  'Triple GLP-1 / GIP / glucagon receptor agonist for metabolic research.',
  'Best seller',
  'metabolic',
  'Metabolic Research',
  '2381089-83-2',
  '4,731 Da',
  'PP-2026-001',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 28 days',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Triple-receptor (GLP-1 / GIP / glucagon)', 'Metabolic & adiposity models', 'Comparative incretin research']::text[],
  array['Fat-metabolism and visceral adiposity models', 'Appetite and caloric-intake signalling', 'Metabolic markers (lipids, waist, energy expenditure)', 'Comparison with dual- and mono-agonist incretin peptides']::text[],
  'Retatrutide is a synthetic tri-agonist research peptide that engages GLP-1, GIP, and glucagon receptors in a single molecule. That three-pathway profile distinguishes it from earlier incretin tools such as semaglutide (GLP-1 only) and tirzepatide (GLP-1/GIP), and is why it is widely used in metabolic, appetite, and body-composition research models. Supplied as a lyophilised vial for laboratory reconstitution.',
  'The triple-receptor research peptide at the centre of modern metabolic and incretin signalling studies.',
  '#f7c04a',
  true,
  0
),
(
  'mots',
  'MOTS-C',
  array['MOTS-c', 'Mitochondrial ORF of the Twelve S rRNA type-c']::text[],
  'Mitochondrial-derived peptide for cellular energy and metabolic research.',
  'Cellular',
  'metabolic',
  'Mitochondrial Research',
  '1627580-64-6',
  '1,697 Da',
  'PP-2026-002',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 28 days',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Mitochondrial-encoded peptide', 'Cellular energy & metabolism', 'Longevity pathway models']::text[],
  array['Cellular energy regulation', 'Metabolic flexibility and AMPK-linked models', 'Exercise and stress-adaptation research', 'Ageing and mitochondrial signalling studies']::text[],
  'MOTS-C is an endogenous mitochondrial-derived peptide (MDP) encoded in the mitochondrial genome — unusual among mammalian peptides, which are typically nuclear-encoded. First characterised in 2015, it has become a core tool for labs studying cellular energy regulation, metabolic function, and longevity-linked mitochondrial signalling. Supplied lyophilised for in-vitro research use.',
  'A mitochondrial-derived peptide at the forefront of cellular metabolism and energy-pathway research.',
  '#e8a020',
  true,
  1
),
(
  'cjc',
  'CJC + IPA',
  array['CJC-1295 no DAC + Ipamorelin', 'CJC/IPA blend']::text[],
  'Dual GH-axis secretagogue blend for endocrine pathway research.',
  'Research duo',
  'growth',
  'Growth Hormone Research',
  null,
  'Blend',
  'PP-2026-003',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 28 days',
  'Bacteriostatic water (recommended)',
  '[{"name":"CJC-1295 (no DAC)","note":"GHRH analogue component"},{"name":"Ipamorelin","note":"Selective GHS-R agonist component"}]'::jsonb,
  array['GH-axis signalling', 'Pulsatile secretagogue models', 'Endocrine pathway research']::text[],
  array['Growth-hormone release dynamics', 'GHRH + ghrelin-receptor co-stimulation models', 'IGF-1 pathway research', 'Recovery and conditioning study designs']::text[],
  'CJC + IPA combines CJC-1295 without DAC (a GHRH analogue) with Ipamorelin (a selective growth-hormone secretagogue receptor agonist) in one research vial. The blend is used to study synergistic GH-axis signalling — GHRH-pathway stimulation plus ghrelin-receptor activation — without the extended half-life of DAC-modified CJC. Ideal for labs running pulsatile GH and endocrine pathway protocols.',
  'The dual secretagogue blend trusted for GH-axis signalling and endocrine pathway research.',
  '#f7c04a',
  true,
  2
),
(
  'ghk',
  'GHK-Cu',
  array['Copper tripeptide-1', 'Glycyl-L-histidyl-L-lysine copper']::text[],
  'Endogenous copper tripeptide for matrix signalling and dermal research.',
  'Copper',
  'repair',
  'Skin & Cellular Research',
  '49557-75-7',
  '340 Da',
  'PP-2026-004',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 8–12 weeks',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Collagen & elastin signalling', 'Wound-healing models', 'Gene-expression research']::text[],
  array['Collagen and elastin synthesis in dermal fibroblasts', 'Wound healing and epidermal repair models', 'Inflammatory signalling in ageing tissue', 'Gene-expression modulation linked to cellular renewal']::text[],
  'GHK-Cu is a naturally occurring copper tripeptide whose plasma concentration declines with age. It is studied for collagen and elastin synthesis, wound healing, inflammatory modulation, and broad gene-expression effects in dermal and tissue-repair research. Research-grade lyophilised peptide supports controlled laboratory protocols beyond low-dose cosmetic formulations.',
  'The copper-binding tripeptide essential for matrix signalling and cellular repair research.',
  '#d98e1b',
  true,
  3
),
(
  'tesa',
  'Tesamorelin',
  array['GHRH analogue', 'TH9507']::text[],
  'Stabilised GHRH analogue for visceral adiposity and GH-axis research.',
  'GHRH',
  'growth',
  'Metabolic Research',
  '218949-48-5',
  '5,135 Da',
  'PP-2026-005',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 28 days',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Visceral adipose research', 'GH / IGF-1 axis', 'Body-composition models']::text[],
  array['Visceral adipose tissue (VAT) reduction models', 'Body recomposition vs gross weight change', 'Endogenous GH and IGF-1 elevation', 'Recovery and conditioning pathway studies']::text[],
  'Tesamorelin is a stabilised analogue of growth hormone-releasing hormone (GHRH). Research interest centres on its preferential effect on visceral adipose tissue rather than broad appetite suppression — distinguishing it from GLP-1-class compounds. It is widely used in body-composition, GH/IGF-1 axis, and metabolic distribution studies.',
  'A GHRH analogue widely used in lipid-metabolism and endocrine signalling research.',
  '#e8a020',
  true,
  4
),
(
  'klow',
  'KLOW',
  array['KLOW blend', 'GHK-Cu / BPC-157 / TB-500 / KPV']::text[],
  'Four-peptide blend for tissue repair, inflammation, and recovery research.',
  'Signature',
  'recovery',
  'Tissue Repair Research',
  null,
  'Blend',
  'PP-2026-006',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 28 days',
  'Bacteriostatic water (recommended)',
  '[{"name":"GHK-Cu","amount":"50 mg"},{"name":"BPC-157","amount":"10 mg"},{"name":"TB-500","amount":"10 mg"},{"name":"KPV","amount":"10 mg"}]'::jsonb,
  array['Structural repair + inflammation', 'Multi-pathway stack', 'Gut-barrier & recovery models']::text[],
  array['Tissue regeneration and remodelling', 'Anti-inflammatory and immune-modulation models', 'Gut-barrier and barrier-integrity research', 'Combined dermal + systemic recovery protocols']::text[],
  'KLOW is a four-peptide research blend combining GHK-Cu, BPC-157, TB-500, and KPV in a single vial. Where GLOW is positioned around dermal and structural repair, KLOW extends the stack with KPV for broader anti-inflammatory, gut-barrier, and recovery research. Designed for protocols that need structural repair and inflammation control together.',
  'Our signature multi-peptide blend for advanced cellular signalling and recovery research.',
  '#f7c04a',
  true,
  5
),
(
  'tb',
  'TB-500',
  array['Thymosin beta-4 fragment', 'TB4 fragment']::text[],
  'Thymosin β4 fragment for actin regulation and tissue research models.',
  'Tissue models',
  'recovery',
  'Tissue Repair Research',
  '77591-33-4',
  '4,963 Da',
  'PP-2026-007',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 28 days',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Actin regulation', 'Cell-migration studies', 'Angiogenic research models']::text[],
  array['Actin binding and cytoskeletal dynamics', 'Cell migration and tissue remodelling', 'Angiogenesis and wound-healing models', 'Soft-tissue and connective-tissue research']::text[],
  'TB-500 is a synthetic fragment related to thymosin beta-4, studied for actin regulation, cell migration, and tissue-remodelling pathways. It is a staple compound in angiogenesis, wound-healing, and connective-tissue research models, often paired with BPC-157 in multi-pathway repair protocols.',
  'The thymosin beta-4 fragment essential for actin regulation and tissue research models.',
  '#d98e1b',
  true,
  6
),
(
  'bpc',
  'BPC-157',
  array['Body Protection Compound-157', 'PL 14736']::text[],
  'Gastric pentadecapeptide for angiogenic and tissue-repair research.',
  'Popular',
  'repair',
  'Tissue Repair Research',
  '137525-51-0',
  '1,419 Da',
  'PP-2026-008',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 8–12 weeks',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Multi-tissue repair models', 'Angiogenic pathway research', 'GI & musculoskeletal studies']::text[],
  array['Muscle, tendon, and ligament repair models', 'Gastrointestinal tissue research', 'Angiogenesis and cytoprotection', 'Inflammatory signalling in injury models']::text[],
  'BPC-157 (Body Protection Compound-157) is a synthetic pentadecapeptide derived from a sequence found in gastric juice. It is one of the most extensively studied repair compounds in peptide research, with activity across musculoskeletal, gastrointestinal, and angiogenic models — valued for multi-system tissue-repair protocols rather than a single-target pathway.',
  'The gastric pentadecapeptide at the centre of angiogenic pathway and tissue research.',
  '#e8a020',
  true,
  7
),
(
  'cagri',
  'Cagrilintide',
  array['Long-acting amylin analogue']::text[],
  'Long-acting amylin analogue for satiety and metabolic pathway research.',
  'New drop',
  'metabolic',
  'Metabolic Research',
  null,
  '4,409 Da',
  'PP-2026-009',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 8–12 weeks',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Amylin receptor pathway', 'Satiety & gastric-emptying models', 'Combination metabolic research']::text[],
  array['Appetite and satiety signalling via amylin', 'Body-weight reduction models (mono & combo)', 'Complementary mechanism to GLP-1 agonists', 'Post-meal glycaemic and gastric-emptying studies']::text[],
  'Cagrilintide is a long-acting analogue of amylin — a pancreatic hormone co-secreted with insulin that contributes to satiety, gastric emptying, and post-meal glucose control. Unlike native amylin, it is engineered for extended research dosing. Primary interest is as a complementary mechanism to GLP-1 agonists (separate amylin pathway), including combination designs studied in modern weight-management research.',
  'A long-acting amylin analogue advancing metabolic and appetite-pathway research models.',
  '#f7c04a',
  true,
  8
),
(
  'mt2',
  'MT-2',
  array['Melanotan II', 'Melanotan 2', 'MT-II']::text[],
  'Non-selective melanocortin agonist for pigmentation and receptor research.',
  'New drop',
  'recovery',
  'Melanocortin Research',
  '121062-08-6',
  '1,024 Da',
  'PP-2026-010',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 8–12 weeks',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Melanogenesis models', 'MC1R–MC5R signalling', 'Appetite & arousal pathway research']::text[],
  array['Melanin synthesis and pigmentation models', 'Melanocortin receptor pharmacology (MC1R–MC5R)', 'Appetite modulation research', 'Central melanocortin system studies']::text[],
  'Melanotan II (MT-2) is a synthetic analogue of α-melanocyte-stimulating hormone (α-MSH). As a non-selective melanocortin receptor agonist, it is studied for melanogenesis, appetite signalling, and broader melanocortin pharmacology. Distinct from Melanotan I (afamelanotide), which is more MC1R-selective.',
  'The melanocortin analogue used widely in pigmentation and receptor-pathway research.',
  '#d98e1b',
  true,
  9
),
(
  'bac',
  'BAC Water',
  array['Bacteriostatic water', '0.9% benzyl alcohol water']::text[],
  'Bacteriostatic water for laboratory reconstitution of lyophilised peptides.',
  'Essential',
  'repair',
  'Lab Supplies',
  null,
  'N/A',
  'PP-2026-011',
  'Sterile solution',
  'USP-grade solvent',
  'Room temperature — protect from light',
  'N/A — use as directed for reconstitution',
  'Use to reconstitute lyophilised research peptides',
  '[]'::jsonb,
  array['Peptide reconstitution', 'Lab preparation essential', 'Sterile research solvent']::text[],
  array['Reconstitution of lyophilised peptides', 'Standard laboratory sample preparation']::text[],
  'Bacteriostatic water is sterile water containing 0.9% benzyl alcohol as a preservative. It is the standard solvent for reconstituting lyophilised research peptides in the lab. Pair with any Primal Peps vial before assay or protocol work.',
  'The essential bacteriostatic water for reconstituting lyophilised research peptides.',
  '#e8a020',
  true,
  10
),
(
  'glow',
  'GLOW',
  array['GLOW blend', 'GHK-Cu / BPC-157 / TB-500']::text[],
  'Three-peptide blend for skin, matrix, and structural repair research.',
  'Blend',
  'repair',
  'Tissue Repair Research',
  null,
  'Blend',
  'PP-2026-012',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 8–12 weeks',
  'Bacteriostatic water (recommended)',
  '[{"name":"GHK-Cu","amount":"50 mg"},{"name":"BPC-157","amount":"10 mg"},{"name":"TB-500","amount":"10 mg"}]'::jsonb,
  array['Dermal structural repair', 'Collagen + angiogenesis stack', 'Pre-blended research convenience']::text[],
  array['Skin rejuvenation and dermal matrix models', 'Collagen / elastin signalling (GHK-Cu)', 'Cytoprotection and inflammation (BPC-157)', 'Cell migration and angiogenic remodelling (TB-500)']::text[],
  'GLOW combines GHK-Cu, BPC-157, and TB-500 in one pre-blended research vial. Each component covers a distinct pathway — structural protein signalling, cytoprotection / inflammatory modulation, and angiogenic cell-migration — for labs studying skin, matrix, and structural repair without compounding three separate vials.',
  'A multi-peptide blend formulated for advanced skin, matrix, and cellular repair research.',
  '#f7c04a',
  true,
  11
),
(
  'nad',
  'NAD+',
  array['Nicotinamide adenine dinucleotide', 'β-NAD']::text[],
  'Essential coenzyme for cellular energy and redox-pathway research.',
  'Cellular',
  'metabolic',
  'Mitochondrial Research',
  '53-84-9',
  '663 Da',
  'PP-2026-013',
  'Lyophilised powder',
  '99%+',
  '-20 °C — protect from light & moisture',
  '2–8 °C — use within 28 days',
  'Bacteriostatic water (recommended)',
  '[]'::jsonb,
  array['Cellular energy metabolism', 'Redox & sirtuin pathways', 'Mitochondrial research staple']::text[],
  array['Cellular energy and ATP-linked pathways', 'Redox balance and electron-transfer research', 'Sirtuin and NAD+-dependent enzyme studies', 'Ageing and metabolic stress models']::text[],
  'NAD+ (nicotinamide adenine dinucleotide) is a central coenzyme in cellular energy metabolism and redox chemistry. Research use spans mitochondrial function, sirtuin activity, and metabolic stress models. Supplied as a high-purity lyophilised research compound for laboratory reconstitution.',
  'The essential coenzyme at the centre of cellular energy and redox-pathway research.',
  '#e8a020',
  true,
  12
)
on conflict (id) do update set
  name = excluded.name,
  aka = excluded.aka,
  sub = excluded.sub,
  tag = excluded.tag,
  cat = excluded.cat,
  category_label = excluded.category_label,
  cas = excluded.cas,
  mw = excluded.mw,
  lot = excluded.lot,
  form = excluded.form,
  purity = excluded.purity,
  storage_lyophilised = excluded.storage_lyophilised,
  storage_reconstituted = excluded.storage_reconstituted,
  reconstitution = excluded.reconstitution,
  composition = excluded.composition,
  perks = excluded.perks,
  research_focus = excluded.research_focus,
  description = excluded.description,
  story = excluded.story,
  hue = excluded.hue,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.product_variants (
  product_id, variant_key, label, price, img, stock, active, sort_order
) values
(
  'reta',
  '5mg',
  '5MG',
  119,
  'products/RETATRUTIDE.png',
  100,
  true,
  0
),
(
  'reta',
  '10mg',
  '10MG',
  169,
  'products/RETATRUTIDE-10MG.png',
  100,
  true,
  1
),
(
  'mots',
  '5mg',
  '5MG',
  79,
  'products/MOTS-C.png',
  100,
  true,
  0
),
(
  'mots',
  '10mg',
  '10MG',
  109,
  'products/MOTS-C-10MG.png',
  100,
  true,
  1
),
(
  'cjc',
  '5mg',
  '5MG',
  89,
  'products/CJC-IPA.png',
  100,
  true,
  0
),
(
  'cjc',
  '10mg',
  '10MG',
  119,
  'products/CJC-IPA-10MG.png',
  100,
  true,
  1
),
(
  'ghk',
  '50mg',
  '50MG',
  65,
  'products/GHK-CU.png',
  100,
  true,
  0
),
(
  'tesa',
  '5mg',
  '5MG',
  95,
  'products/TESAMORELIN.png',
  100,
  true,
  0
),
(
  'tesa',
  '10mg',
  '10MG',
  129,
  'products/TESAMORELIN-10MG.png',
  100,
  true,
  1
),
(
  'klow',
  '70mg',
  '70MG',
  85,
  'products/KLOW-70.png',
  100,
  true,
  0
),
(
  'klow',
  '80mg',
  '80MG',
  99,
  'products/KLOW-80.png',
  100,
  true,
  1
),
(
  'tb',
  '5mg',
  '5MG',
  75,
  'products/TB-500.png',
  100,
  true,
  0
),
(
  'tb',
  '10mg',
  '10MG',
  99,
  'products/TB-500-10MG.png',
  100,
  true,
  1
),
(
  'bpc',
  '5mg',
  '5MG',
  69,
  'products/BPC-157.png',
  100,
  true,
  0
),
(
  'bpc',
  '10mg',
  '10MG',
  89,
  'products/BPC-157-10MG.png',
  100,
  true,
  1
),
(
  'cagri',
  '10mg',
  '10MG',
  109,
  'products/CAGRILINTIDE.png',
  100,
  true,
  0
),
(
  'mt2',
  '10mg',
  '10MG',
  59,
  'products/MT-2.png',
  100,
  true,
  0
),
(
  'bac',
  'std',
  'Standard',
  25,
  'products/BAC-WATER.png',
  100,
  true,
  0
),
(
  'glow',
  '70mg',
  '70MG',
  95,
  'products/GLOW.png',
  100,
  true,
  0
),
(
  'nad',
  '500mg',
  '500MG',
  89,
  'products/NAD.png',
  100,
  true,
  0
)
on conflict (product_id, variant_key) do update set
  label = excluded.label,
  price = excluded.price,
  img = excluded.img,
  stock = excluded.stock,
  active = excluded.active,
  sort_order = excluded.sort_order;
